# === Valid/Normal Cases (Regular input values within acceptable limits) ===
VALID = [
    [
        "TTTTTTTTTT",
        "T...+...RT",
        "T...~...RT",
        "T...R.T.RT",
        "T.T.LTT.RT",
        "T.x...*.RT",
        "T.......RT",
        "T.......RT",
        "T.......RT",
        "TTTTTTTTTT",
    ],
    [
        "TTTTTTTTTT",
        "T.....~+RT",
        "T...R.TTRT",
        "T.....T.RT",
        "T.x.....RT",
        "T.~.....RT",
        "T.~.....RT",
        "T..*TTT.RT",
        "TL......RT",
        "TTTTTTTTTT",
    ],
    [
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
        "T.LTTTTTTTTTRRRRRRRRRRRRRRRRT",
        "T.TTTTTTTTTRTTTTT.......RRRRT",
        "T.TTTTTTTTTRT....+......R..RT",
        "T.T...T...T.R........RRRR..RT",
        "T...T...T...R....x..R....*.RT",
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
        "T+....RRRRRRRRRRRRRRR..RR...T",
        "TRRR.R.................RRRR.T",
        "TRRR..x....RRRRRRRRRRR....*.T",
        "TRRRRRR....RRRRRRRRRRR......T",
        "TRRRR.R.+..RRRRRRRRRRR......T",
        "RRRRRR.RRRRRRRRRRRRRRRRRRRRRR",
        "T....RRRRRRRRRRRRRRRRRRRRR..T",
        "T....R.RRRRRRRRRRRRRRRRRRR+.T",
        "T....R.RRRRRRRRRRRRRRRRR.R..T",
        "T..+..~RRRRRRRRRRRRRRRRRRRR.T",
        "RRRRRRRRRRRRRRRRRRRRRRRRR.RRR",
        "T..RRRRRRRRRRRRRRRRRRRRRR~R.T",
        "T.+RRRRRRRRRRRRRRRRRRRRRR.+.T",
        "T..RRRRRRR~~~~~~~~RRRRRRR.*.T",
        "T..RRRRRRR~~~~~~~~RRRRRRRRR.T",
        "RRRRRRRRRR~~~~~~~~RRRRRRRRRRR",
        "T..RRRRRRRRRRRRRRRRRRRRRRRR.T",
        "T..RRRRRRRRRRRRRRRRRRRRRRRR.T",
        "T.....+..RRRRRRRRRRRRRRRRRR.T",
        "T..RRRRRRRRRRRRRRRRRRRRRRRR.T",
        "T..RRRRRRRRRRRRRRRRRRRRRRRR.T",
        'T..RRRRRRRRRRRRRRRRRRRRRRR+~T',
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    ],
    [
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
        "R...........................R",
        "R.x........................+R",
        "R........RRRRRRRRRRRRRRRRRRRR",
        "R+.R...R.................R.LR",
        "R.R..R.R.RRRRRRRRRRRRRR..R..R",
        "R........TTTTTTTTTTTTTT..RRRR",
        "R.R.RR......................R",
        "R...R....TTTTTTTTTTTTTTTTTTTR",
        "R..R.....TTTTTTTTTTTTTTTTTTTR",
        "RRR....TTT..................R",
        "R.....T~~~T.................R",
        "R.....T~~~T.......*.........R",
        "R.....T~~~T......TTTTTTTTTTTR",
        "R.x....TTT..+....T~~~~~~~~~~R",
        "RRRRRRRRRR.......T~~~~~~~~~~R",
        "RTTTTTTTTR.......TTTTTTTTTTTR",
        "R.+..T..TR..................R",
        "R....T..TR..............x...R",
        "RRRRRR..TR.RRRRRRRRRRRRRRRRRR",
        "R.....+.TR.RTTTTTTTTTTTTTT..R",
        "RTTTT...TR.RT...............R",
        "R........R.RT.....*.TTTTTTTTR",
        "R......RRR.RT.......TTTTTTTTR",
        "RRRRRR.....RT.......TTTTTTTTR",
        "R~~~~R.....RT...............R",
        "R~~~~R.....RRRRRRRRRRRR..+..R",
        "R.RRRRR....RRRRRRRRRRRR.....R",
        "R.....+....R....+...........R",
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    ],
]

# === Boundary Cases (Values at the boundaries of the acceptable limits) ===
## Blank Case
BLANK = [
    [''],
]
## Other Edge Cases
EDGE = [
    ['L'],
    [
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
        "T.LTTTTTTTTTRRRRRRRRRRRRRRRRT",
        "T.TTTTTTTTTRTTTTT.......RRRRT",
        "T.TTTTTTTTTRT....+......R..RT",
        "T.T...T...T.R........RRRR..RT",
        "T...T...T...R....x..R....*.RT",
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
        "T+....RRRRRRRRRRRRRRR..RR...T",
        "TRRR.R.................RRRR.T",
        "TRRR..x....RRRRRRRRRRR....*.T",
        "TRRRRRR....RRRRRRRRRRR......T",
        "TRRRR.R.+..RRRRRRRRRRR......T",
        "RRRRRR.RRRRRRRRRRRRRRRRRRRRRR",
        "T....RRRRRRRRRRRRRRRRRRRRR..T",
        "T....R.RRRRRRRRRRRRRRRRRRR+.T",
        "T....R.RRRRRRRRRRRRRRRRR.R..T",
        "T..+..~RRRRRRRRRRRRRRRRRRRR.T",
        "RRRRRRRRRRRRRRRRRRRRRRRRR.RRR",
        "T..RRRRRRRRRRRRRRRRRRRRRR~R.T",
        "T.+RRRRRRRRRRRRRRRRRRRRRR.+.T",
        "T..RRRRRRR~~~~~~~~RRRRRRR.*.T",
        "T..RRRRRRR~~~~~~~~RRRRRRRRR.T",
        "RRRRRRRRRR~~~~~~~~RRRRRRRRRRR",
        "T..RRRRRRRRRRRRRRRRRRRRRRRR.T",
        "T..RRRRRRRRRRRRRRRRRRRRRRRR.T",
        "T.....+..RRRRRRRRRRRRRRRRRR.T",
        "T..RRRRRRRRRRRRRRRRRRRRRRRR.T",
        "T..RRRRRRRRRRRRRRRRRRRRRRRR.T",
        'T..RRRRRRRRRRRRRRRRRRRRRRR+~T',
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    ],
]

# === Corner Cases (Values that represent extreme or unusual scenarios that could affect the unit or even the system) ===
## Huge Cases
HUGE = [
    [
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
        "R...........................R",
        "R.x........................+R",
        "R........RRRRRRRRRRRRRRRRRRRR",
        "R+.R...R.................R.LR",
        "R.R..R.R.RRRRRRRRRRRRRR..R..R",
        "R........TTTTTTTTTTTTTT..RRRR",
        "R.R.RR......................R",
        "R...R....TTTTTTTTTTTTTTTTTTTR",
        "R..R.....TTTTTTTTTTTTTTTTTTTR",
        "RRR....TTT..................R",
        "R.....T~~~T.................R",
        "R.....T~~~T.......*.........R",
        "R.....T~~~T......TTTTTTTTTTTR",
        "R.x....TTT..+....T~~~~~~~~~~R",
        "RRRRRRRRRR.......T~~~~~~~~~~R",
        "RTTTTTTTTR.......TTTTTTTTTTTR",
        "R.+..T..TR..................R",
        "R....T..TR..............x...R",
        "RRRRRR..TR.RRRRRRRRRRRRRRRRRR",
        "R.....+.TR.RTTTTTTTTTTTTTT..R",
        "RTTTT...TR.RT...............R",
        "R........R.RT.....*.TTTTTTTTR",
        "R......RRR.RT.......TTTTTTTTR",
        "RRRRRR.....RT.......TTTTTTTTR",
        "R~~~~R.....RT...............R",
        "R~~~~R.....RRRRRRRRRRRR..+..R",
        "R.RRRRR....RRRRRRRRRRRR.....R",
        "R.....+....R....+...........R",
        "RRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    ],
]

# === Invalid/Error Cases (Values that fall outside the valid range) ===
## Type Errors
TYPE_ERRORS = [
    [111, 1111, 1111, 1111],
    [111, 1111, 1111, "1111"],
    [111, 1111, [1111], "1111"],
    [111, 1111, ["1111"], "1111"],
    ["111", 1111, ["1111"], "1111"],
    [(1, 2, 3)],
    [("1", 2, 3)],
    [("1", "2", "3")],
    [["1", "2", "3"], "123"],
    [["1", "2", "3"], (1, 2, 3)],
    [[1, 2, 3], (1, 2, 3)],
    [[1, 2, 3], ("1", "2", "3")],
    (111, 1111, 1111, 1111),
    (111, 1111, 1111, "1111"),
    (111, 1111, [1111], "1111"),
    (111, 1111, ["1111"], "1111"),
    ("111", 1111, ["1111"], "1111"),
    ((1, 2, 3)),
    (("1", 2, 3)),
    (("1", "2", "3")),
    (["1", "2", "3"], "123"),
    (["1", "2", "3"], (1, 2, 3)),
    ([1, 2, 3], (1, 2, 3)),
    ([1, 2, 3], ("1", "2", "3")),
]
## Value Errors
VALUE_ERRORS_IMPOPER = [
    ['...L...', '...+...', '...+..'],
    ['...L...', '...+...', '...+....'],
    ['L', '.+', '.'],
]
VALUE_ERRORS_MUTATED = [
    ['...L..p', '...+...', '...+..'],
    ['...L...', '.d.+...', '...+....'],
    ['L', '.+', 'l'],
]
