MAP_INSTRUCTIONS_GAP = 5
SPACE = '\U00003000'

# === ASCII ===
# TILES
EMPTY_TILE_ASCII = '.'
LARO_CRAFT_TILE_ASCII = 'L'
TREE_TILE_ASCII = 'T'
MUSHROOM_TILE_ASCII = '+'
ROCK_TILE_ASCII = 'R'
WATER_TILE_ASCII = '~'
PAVED_TILE_ASCII = '_'
# ITEMS
AXE_ITEM_ASCII = 'x'
FLAMETHROWER_ITEM_ASCII = '*'

# SET OF ALL VALID TILES
VALID_TILES = {
    EMPTY_TILE_ASCII,
    LARO_CRAFT_TILE_ASCII,
    TREE_TILE_ASCII,
    MUSHROOM_TILE_ASCII,
    ROCK_TILE_ASCII,
    WATER_TILE_ASCII,
    PAVED_TILE_ASCII,
    AXE_ITEM_ASCII,
    FLAMETHROWER_ITEM_ASCII,
}

# SET OF ALL VALID ITEMS
VALID_ITEMS = {
    AXE_ITEM_ASCII,
    FLAMETHROWER_ITEM_ASCII,
}